### ISSUE TITLE
Sync not work when file name contains space

### ISSUE THREAD

**Issue by tensecor** [jaliste/gedit-synctex-plugin#4] opened 2011-05-18 06:42 UTC
This plugin dose not work when the tex file name contains space.

**Comment by jaliste** [comment] 2011-05-26 15:44
Hi, I can't reproduce the bug... which version of the plugin are you using? Please note that the version in github is only there for historical purposes you should be using the official version from either your distribution or from the gnome servers

**Comment by tensecor** [comment] 2011-05-27 05:11
Thanks for your replay. 
My gedit and SyncTeX plugin is of version 3.0.2 and are all downloaded  form archlinux package repository. 
A simple file to that makes forward search and backward search not to work list as follows:

%%"test space.tex"
\documentclass{article}
\begin{document}
Hello world.\\
Hello world.
\end{document}

After compile "test space.tex" with "pdflatex --synctx=1 "test space.tex" ", press C_A_F in gedit and nothing happens, and click in evince, nothing happens too. But when I change the file name to "test.tex", the problem disappears and forward search and backward search works fine.
When I upgrade gedit and the SyncTeX plugin to the latest version 3.0.3, the same problem is still there.

But a strange thing happens after I upgrade evince to the latest version 3.0.2; the problem is gone. I don't know my evince's old version, but I know evince 2.32.0 has this problem since this is the version of my laptop's evince. 

So I guess that this is not a bug in gedit's SyncTeX plugin, but a bug in evince, and it's fixed in the latest version of evince.

**Comment by jaliste** [comment] 2011-05-27 12:57
Thanks for the feedback. Keep in Mind that Gedit-synctex 3.0.X is compatible with Evince 3.0 Only. Not with evince 2.32... There is a change in the API of Synctex I made so the experience is better under gnome-shell. So, I think we can close this. In the future, please submit bugs to Gnome bugzilla.

**Closed as completed by jaliste** 2011-05-27 12:57 UTC
